name: useful_utilities
description: UsefulUtilities is a class that contains useful utilities for the Flutter app
version: 0.0.1
homepage: https://github.com/AnmolSethi/useful_utilities

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
